### ISSUE TITLE
[linux] Add linux framebuffer driver

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#152]
**Requirements:**

- In the Linux platform, the framebuffer driver code is compiled by default and coexist with the x11 driver.
- When the application is running in the Linux platform, if the x11 server cannot connect, try switching to the framebuffer driver, and show the built-in cursor.

**TODO:**

- [x] Add events driver code in: src/platform/linux/linux_events.c
- [x] Add keyboard driver code in: src/platform/linux/linux_keyboard.c
- [x] Add video driver code in: src/platform/linux/linux_fbdisplay.c
- [x] Add mouse driver code in: src/platform/linux/linux_mouse.c

**Reference:**

- https://github.com/lc-soft/LCUI/blob/v0.15.0/src/output/framebuffer.c
- https://github.com/lc-soft/LCUI/blob/v0.15.0/src/input/keyboard.c
- https://github.com/lc-soft/LCUI/blob/v0.15.0/src/input/mouse.c
