### ISSUE TITLE
LCUI 3.0 development plan

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#239]
LCUI has the following problems:

- There are multiple API design styles.
- The header file dependency is complicated.
- Some modules have a higher degree of coupling.
- Compilation is slow.

We plan to solve them in version 3.0. The main method is to split LCUI into multiple libraries so that LCUI has the following features:

- **Unified API design style.** Improve development experience and efficiency.
- **Faster compilation speed.** The header file becomes simpler, which improves the compilation speed.
- **Better modularity.** For users, they can modify and customize the library in LCUI according to their needs, or even replace it with a better open source library of the same kind. For us, we can give some libraries to other contributors to develop and maintain to achieve a win-win cooperation.

### Directory structure

```text
include/
    example.h
src/
    private.h
    file1.c
    file2.c
    ...
test/
    test.c
    test_???.c
    test_???.c
    ...
LICENSE
README.md
xmake.lua
```

### API design

We can refer to the API design of the following open source projects:

- libgit2: https://libgit2.org/libgit2/
- LevelDB: https://github.com/google/leveldb/blob/master/include/leveldb/c.h

## LCUI project design

**Directory Structure:**

```text
include/
    LCUI/
        util.h
        thread.h
        app.h
        paint.h
        image.h
        css.h
        font.h
        layout.h
        ui.h
        ...
    LCUI.h
lib/
    util/
    thread/
    app/
    paint/
    image/
    css/
    ui/
    font/
    layout/
    ...
src/
    ...
```

**Coding style:**

Follow the current coding style.

**API design style:**

It is the same as the API design style of the library. In order to reduce the changes during the upgrade of the LCUI application, we will provide header files that containing the CamelCase naming style API.

## TODO

The following list shows the work content and progress of this plan:

- [x] Coding style
- [x] API design style
- [x] Use xmake to build project
- [ ] Update README.md
- [x] Write a sample program that shows how to draw using the Cario graphics library
- [ ] Add Libraries
    - [x] yutil
    - [x] pandagl
    - [ ] css
    - [x] platform
    - [x] ui
    - [ ] thread
    - [ ] image
    - [x] font

**Comment by dossalab** [comment]
Just out of curiosity - why complicate build process so much? Why not to use any cross-platform build system (meson, xmake, may be even simple makefiles?). I like LCUI, but I feel like installing it in the past was easier (at least on linux)

**Comment by lc-soft** [comment]
> Just out of curiosity - why complicate build process so much? Why not to use any cross-platform build system (meson, xmake, may be even simple makefiles?). I like LCUI, but I feel like installing it in the past was easier (at least on linux)

Because the building tools I knew before I created LCUI project were autotool and Visual Studio, so I used them to build LCUI in Linux and Windows respectively. As the project is updated, the build configuration becomes more and more complex.

In the 3.0 development plan, I plan to use cross platform building tools to build LCUI. The new source code organization may allow me to compile LCUI by adding a simple configuration without spending too much time researching the documentation of the build tool.

**Comment by WhoAteDaCake** [comment]
I'm not a C programmer, so it might be a silly question, but why prefix all the names with "lib" prefix? By defition this is a library, so why specify it on all entities

**Comment by lc-soft** [comment]
> I'm not a C programmer, so it might be a silly question, but why prefix all the names with "lib" prefix? By defition this is a library, so why specify it on all entities

There are two reasons for using the lib prefix: 

- Using LCUI as the prefix name is too long, so temporarily use lib instead of LCUI as the prefix.
- The lib prefix can describe that this identifier comes from a third-party library, rather than the code of the project itself.

For this prefix name problem, we have the following solutions: 

- Choose a new name for LCUI. If the new name of LCUI can be abbreviated by one letter, as in `Qt`, it can be abbreviated as `q`, then this letter can be prefixed with it instead of lib. 
- Do not use lib as a prefix.

**Comment by FireInIceCode** [comment]
I want to know more about the basic tools library to decide whether I will try realizing it.
By the way, the website says all the contributors of the project are Chinese, so must I use English when I write comments and documents?

**Comment by lc-soft** [comment]
> the website says all the contributors of the project are Chinese,
@FireInIceCode The website you mentioned is [summer.iscas.ac.cn](https://summer.iscas.ac.cn/#/?lang=en)?

**Comment by FireInIceCode** [comment]
No, the 

> > the website says all the contributors of the project are Chinese,
> 
> @FireInIceCode The website you mentioned is [summer.iscas.ac.cn](https://summer.iscas.ac.cn/#/?lang=en)?

No, I mean https://lcui.org/

**Comment by lc-soft** [comment]
@FireInIceCode 

> No, I mean https://lcui.org/

你贴的是 lcui.lc-soft.io 中文主页上的内容，不是 lcui.org。

>  so must I use English when I write comments and documents?

优先用中文。

**Comment by Taswen** [comment]
> > Just out of curiosity - why complicate build process so much? Why not to use any cross-platform build system (meson, xmake, may be even simple makefiles?). I like LCUI, but I feel like installing it in the past was easier (at least on linux)
> 
> Because the building tools I knew before I created LCUI project were autotool and Visual Studio, so I used them to build LCUI in Linux and Windows respectively. As the project is updated, the build configuration becomes more and more complex.
> 
> In the 3.0 development plan, I plan to use cross platform building tools to build LCUI. The new source code organization may allow me to compile LCUI by adding a simple configuration without spending too much time researching the documentation of the build tool.

In terms of versatility, I recommend CMake.

**Comment by TheSystemIsCorrupt** [comment]
A video component using small library (https://github.com/cisco/openh264) would be great!

**Comment by WhoAteDaCake** [comment]
> > > Just out of curiosity - why complicate build process so much? Why not to use any cross-platform build system (meson, xmake, may be even simple makefiles?). I like LCUI, but I feel like installing it in the past was easier (at least on linux)
> > 
> > 
> > Because the building tools I knew before I created LCUI project were autotool and Visual Studio, so I used them to build LCUI in Linux and Windows respectively. As the project is updated, the build configuration becomes more and more complex.
> > In the 3.0 development plan, I plan to use cross platform building tools to build LCUI. The new source code organization may allow me to compile LCUI by adding a simple configuration without spending too much time researching the documentation of the build tool.
> 
> In terms of versatility, I recommend CMake.

From what I've seen so far cmake is always horrible to maintain and understand :shrug:

**Comment by lc-soft** [comment]
> In terms of versatility, I recommend CMake.

@Taswen 
 
I've decided to use xmake because I can easily communicate with xmake author about usage issues.

Here is the xmake configuration file: https://github.com/lc-soft/LCUI/blob/v3.0-dev/xmake.lua

**Comment by Taswen** [comment]
> I've decided to use xmake because I can easily communicate with xmake author about usage issues.
> 
> Here is the xmake configuration file: https://github.com/lc-soft/LCUI/blob/v3.0-dev/xmake.lua

That is good. It depends on your convenient of development.
But personally, I still think it will better to provide an option of CMake.
For the following reasons:
1. Many IDEs integrate native support for CMake, such as VS, Clion, QT.
2. At least until now, the number of users using cmake is larger than that using xmake. To use LCUI, some people have to configure and learn xmake (IDE can generate CMAKE configuration) which means that the use cost increases.
3. More general and powerful.

CMake has become the de-facto standard of C/C++ development tools. For further promotion, CMake is still needed.

 Maybe, you can think about it later.

**Comment by Taswen** [comment]
> From what I've seen so far cmake is always horrible to maintain and understand 🤷

Maybe it’s a bit more complicated, but it’s also very useful (just like C++ 🤪).

**Comment by lc-soft** [comment]
@Taswen

xmake supports generating CMakelists.txt file using the `xmake project -k cmakelists` command.

> 1\. Many IDEs integrate native support for CMake, such as VS, Clion, QT.

This is not a necessary reason to use CMake. The IDE can also be used just as a code editor, the only bit of trouble is that we need to open the command line terminal and then type the xmake command if necessary to build the project. In Linux, I use VSCode to edit the code of LCUI and use xmake command to build LCUI in its built-in command line terminal. Such development mode does not affect my development efficiency.

> 2\. At least until now, the number of users using cmake is larger than that using xmake. To use LCUI, some people have to configure and learn xmake (IDE can generate CMAKE configuration) which means that the use cost increases.

As a library, lcui is commonly used in two ways:

1. Download the compiled binary package and extract the header file and library file (`.dll` `,lib` or. `.a` `.so`) from it, and then manually configure the header file directory and library directory of the compiler in your project.
2. Download the source code and compile it manually. In the simplest case, you only need to run the `xmake` command to build LCUI. If you have more needs, it is necessary to learn xmake, and I don't think the learning cost of xmake is high.

> 3\. More general and powerful.

This is not a reason for me to use CMake. I only focus on whether I can describe the build configuration of the project with less and simple code, and I am not interested in whether it is powerful.

**Comment by ecochard** [comment]
As you still in planning, may be you should have a look at Blend2D and think of QuickJS integration.
(I'm not affiliated with them :) )

**Comment by 204065248** [comment]
3.0 支持多窗口吗
