### ISSUE TITLE
Some problems with widgets in the 2.0 scaling mode

### ISSUE THREAD

**Issue by lc-soft** [lc-soft/LCUI#94]
#66

When setting the zoom ratio to 2.0, there are some problems, need to solve them.

**TODO**

- [x] Fix: textview line height and text position invalid
- [x] Fix: scrollbar position is incorrect when mouse dragging
- [x] Fix: widget invalid area is not accurate
- [x] Fix: window height is not equal root widget height
- [x] Fix: loading message box size incorrect
- [x] Fix: textedit cannot support scaling

**Screenshots and GIFs**

![qq 20170617154135](https://user-images.githubusercontent.com/1730073/27251180-2e31e67c-5374-11e7-95ba-ee4c02180d84.png)
![qq 20170617155603](https://user-images.githubusercontent.com/1730073/27251231-7aa75cca-5375-11e7-9856-ec4e7d31126f.png)
![qq 20170617155636](https://user-images.githubusercontent.com/1730073/27251235-8ede5cb6-5375-11e7-93c2-b14f0fedea3b.png)
![qq 20170617155734](https://user-images.githubusercontent.com/1730073/27251240-aec6e20a-5375-11e7-8241-4e077a5742a5.png)

**Comment by lc-soft** [comment]
**Fixed:** textview line height and text position invalid.

![qq 20170617160151](https://user-images.githubusercontent.com/1730073/27251275-63057074-5376-11e7-8fed-58430fff63ba.png)

**Comment by lc-soft** [comment]
When the widget position is not an integer, the calculated invalid area has an error.

``` c
static void test_move_widget( void *arg )
{
	static float x = 10, y = 10;
	Widget_Move( self.widget, x += 0.5f, y += 0.5f );
	LCUITimer_Set( 10, test_move_widget, NULL, FALSE );
	TEST_LOG( "move: %g, %g\n", x, y );
}
```

![test-move-rect](https://user-images.githubusercontent.com/1730073/27513669-0e2022e8-59a2-11e7-8e03-ff9719b7555e.gif)

**Comment by lc-soft** [comment]
The SourceTree user experience like a shit.
